### ISSUE TITLE
why process "pos" in dataset like this?

### ISSUE THREAD

**Issue by tyco986** [UT-Austin-RPL/GIGA#12]
1. Why process "pos" in dataset like the line: 

https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/dataset_voxel.py#L35

2. Why the "self.size" in  

https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/src/vgn/simulation.py#L37

define like this?

3. Why the do not use "pos" in " x, y, z" instead of "i, j k" in following lines?
https://github.com/UT-Austin-RPL/GIGA/blob/d67c4388d334babe6c11c1555a6e848fb4828c84/scripts/construct_dataset_parallel.py#L73

**Comment by Steve-Tod** [comment]
1. Because we want to normalize the `pos` into [-0.5, 0.5].
2. I just adopt the [code of vgn](https://github.com/ethz-asl/vgn/blob/fdd46109ce38a526ed7e2d52336e07e7f0204f17/src/vgn/simulation.py#L28). My understanding is that they just set the size of workspace to be 30cm.
3. I just adopt the [code of vgn](https://github.com/ethz-asl/vgn/blob/fdd46109ce38a526ed7e2d52336e07e7f0204f17/scripts/construct_dataset.py#L29).
