### ISSUE TITLE
Questions about experimental results

### ISSUE THREAD

**Issue by wuzeww** [UT-Austin-RPL/GIGA#7]
Hi，

The results I got with the model you gave are different from those in your paper, and the results are different under different devices. I want to know if you have the same problem at that time. Is this because the test objects are randomly selected and randomly placed? Is the test scene generated each time not fixed, so sometimes the experimental results are different？

Looking forward to your answer. Thank you！

**Comment by Steve-Tod** [comment]
Hi, there is randomness in the `torch_scatter` package we used which can't be removed by setting random seeds. So even we use exactly the same scene setup, the results are still a little bit different. However, there should not be a large difference.  I just ran two experiments and got the following results:

![image](https://user-images.githubusercontent.com/26958167/136416919-87f2802d-703e-4c2d-97b0-91579c08dd18.png)

I use the same random seed here, but get different results which are both significantly higher than the number in the paper. This is because the number given in the paper is the average result of multiple runs with different random seeds (by specifying `--seeds 1 2 3 4 5` in arguments). Different random seeds may give different levels of difficulty.

Also, what do you mean by different devices?

**Comment by wuzeww** [comment]
Thank you very much for your answer, I understand now.

My previous "device" means the result of running under different computers. 

Is your seeds set like this? --num-rounds 100   --seeds [0, 1, 2, 3, 4]
![2021-10-08 10-54-26 的屏幕截图](https://user-images.githubusercontent.com/44798683/136491819-56e89ab3-faad-4571-8b74-d23ba9c68e3a.png)

**Comment by Steve-Tod** [comment]
I don't remember the exact random seeds I used, but you can try these first.

**Comment by wuzeww** [comment]
Ok, thank you!

**Comment by wuzeww** [comment]
Hi！

I have a new question. Are the epoch of GIGA, GIGA-Aff  and VGN the same?  Are they all 20？
